- name: Debian | Add GPG key
  apt_key:
    url: https://packagecloud.io/gpg.key 
    state: present

- name: Debian | Add repository
  repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
  state: present
  filename: {{ debian_grafana_repository_filename }}

- name: Debian | Install Grafana
  apt: 
   name: grafana
   state: installed
   update_cache: yes
   notify:
    - Debian | init grafana service debian

- name: Debian | Allow grafana port in UFW
  ufw:
   rule: allow
   port: {{ grafana_port }}
   proto: tcp
   notify:
    - start grafana service
