- name: Debian | Add GPG key
  apt_key:
    url: {{ deb.grafana_repo_key_url }} 
    state: present

- name: Debian | Add repository
  apt_repository:
    repo: {{ deb.grafana_repo_url }}
    state: present
    filename: {{ deb.debian_grafana_repository_filename }}

- name: Debian | Install Grafana
  apt: 
   name: grafana
   state: installed
   update_cache: yes
   notify:
    - Debian | init grafana service debian

- name: Debian | Allow grafana port in UFW
  ufw:
   rule: allow
   port: {{ deb.grafana_port }}
   proto: tcp
   notify:
    - start grafana service
