- name: RedHat | Add Grafana repository
  yum_repository:
    name: {{ redhat_grafana_repository_name }}
    description: {{ redhat_grafana_repository_name }}
    baseurl: https://packagecloud.io/grafana/stable/el/6/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
       - https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    sslverify: yes
    sslcacert:
       - /etc/pki/tls/certs/ca-bundle.crt

- name: RedHat | Install grafana
  yum:
    name: grafana
    state: installed
    update_cache: yes
    notify:
      - RedHat | init grafana service redhat
# firewalld is inactive by default on redhat disctributions
- name: RedHat | Enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes
    
- name: RedHat | Allow grafana port 
  command: firewall-cmd --permanent --zone=public --add-port=3000/tcp
  notify: 
    - restart firewalld
    - start grafana

