- name: Debian | check whether grafana is already installed
  shell: grafana-cli --help 
  ignore_errors: True
  register: grafana_installed 
  changed_when: false 

- debug:
    msg: 'It seems that grafana is already installed'
  when:  grafana_installed.rc == 0
