
- name: Debian | init grafana service
  command: update-rc.d grafana-server defaults 95 10


- name: RedHat | init grafana service
  systemd:
   state: restarted
   enabled: yes
   daemon_reload: yes
   name: grafana

- name: start grafana service
  service:
   name: grafana
   enabled: yes
   state: started

- name: RedHat | restart firewalld service
  service:
   name: firewalld
   state: restarted   
